package GUI;

import com.formdev.flatlaf.extras.FlatSVGIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author ADMIN
 */
public class NhaCungCap extends javax.swing.JPanel {

    /**
     * Creates new form NhaCungCap
     */
    public NhaCungCap() {
        initComponents();
        addIcon();
        tblNhaCC.setFocusable(false);     
        tblNhaCC.setDefaultEditor(Object.class, null); // set ko cho sửa dữ liệu trên table
        tblNhaCC.getColumnModel().getColumn(1).setPreferredWidth(180);
        tblNhaCC.setFocusable(false);
        tblNhaCC.setAutoCreateRowSorter(true);
    }
    private void addIcon(){
            btnThemNhaCC.setIcon(new FlatSVGIcon("./icon/add.svg"));
            btnSuaNhaCC.setIcon(new FlatSVGIcon("./icon/edit.svg"));
            btnXoaNhaCC.setIcon(new FlatSVGIcon("./icon/delete.svg"));
            btnNhapExcelNCC.setIcon(new FlatSVGIcon("./icon/import_excel.svg"));
            btnXuatExcelNCC.setIcon(new FlatSVGIcon("./icon/export_excel.svg"));

        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTop = new javax.swing.JPanel();
        btnThemNhaCC = new javax.swing.JButton();
        btnSuaNhaCC = new javax.swing.JButton();
        btnXoaNhaCC = new javax.swing.JButton();
        btnNhapExcelNCC = new javax.swing.JButton();
        btnXuatExcelNCC = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnTimKiem = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        asd = new javax.swing.JScrollPane();
        tblNhaCC = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1200, 800));
        setLayout(new java.awt.BorderLayout());

        pnlTop.setBackground(new java.awt.Color(255, 255, 255));
        pnlTop.setPreferredSize(new java.awt.Dimension(1200, 70));

        btnThemNhaCC.setText("Thêm");
        pnlTop.add(btnThemNhaCC);

        btnSuaNhaCC.setText("Sửa");
        btnSuaNhaCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaNhaCCActionPerformed(evt);
            }
        });
        pnlTop.add(btnSuaNhaCC);

        btnXoaNhaCC.setText("Xóa");
        btnXoaNhaCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaNhaCCActionPerformed(evt);
            }
        });
        pnlTop.add(btnXoaNhaCC);

        btnNhapExcelNCC.setText("Nhập excel");
        btnNhapExcelNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapExcelNCCActionPerformed(evt);
            }
        });
        pnlTop.add(btnNhapExcelNCC);

        btnXuatExcelNCC.setText("Xuất excel");
        btnXuatExcelNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatExcelNCCActionPerformed(evt);
            }
        });
        pnlTop.add(btnXuatExcelNCC);

        jLabel1.setText("Tìm kiếm :");
        pnlTop.add(jLabel1);

        btnTimKiem.setMinimumSize(new java.awt.Dimension(200, 30));
        btnTimKiem.setPreferredSize(new java.awt.Dimension(200, 30));
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });
        pnlTop.add(btnTimKiem);

        add(pnlTop, java.awt.BorderLayout.NORTH);

        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 700));

        tblNhaCC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã NCC", "Tên nhà cung cấp", "Địa chỉ", "Email", "Điện thoại"
            }
        ));
        asd.setViewportView(tblNhaCC);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(asd, javax.swing.GroupLayout.DEFAULT_SIZE, 786, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(asd, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSuaNhaCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaNhaCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSuaNhaCCActionPerformed

    private void btnXoaNhaCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaNhaCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaNhaCCActionPerformed

    private void btnNhapExcelNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapExcelNCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNhapExcelNCCActionPerformed

    private void btnXuatExcelNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatExcelNCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXuatExcelNCCActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTimKiemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane asd;
    private javax.swing.JButton btnNhapExcelNCC;
    private javax.swing.JButton btnSuaNhaCC;
    private javax.swing.JButton btnThemNhaCC;
    private javax.swing.JTextField btnTimKiem;
    private javax.swing.JButton btnXoaNhaCC;
    private javax.swing.JButton btnXuatExcelNCC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnlTop;
    private javax.swing.JTable tblNhaCC;
    // End of variables declaration//GEN-END:variables
}
