package GUI;

import com.formdev.flatlaf.extras.FlatSVGIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author ADMIN
 */
public class PhieuXuat extends javax.swing.JPanel {

    /**
     * Creates new form PhieuXuat
     */
    public PhieuXuat() {
        initComponents();
        addIcon();
        tblPhieuXuat.setFocusable(false);     
        tblPhieuXuat.setDefaultEditor(Object.class, null); // set ko cho sửa dữ liệu trên table
        tblPhieuXuat.getColumnModel().getColumn(1).setPreferredWidth(180);
        tblPhieuXuat.setFocusable(false);
        tblPhieuXuat.setAutoCreateRowSorter(true);
    }
    private void addIcon(){
            btnThemPX.setIcon(new FlatSVGIcon("./icon/add.svg"));
            btnChiTietPX.setIcon(new FlatSVGIcon("./icon/edit.svg"));
            btnHuyPX.setIcon(new FlatSVGIcon("./icon/cancel.svg"));
            btnXuatExcelPX.setIcon(new FlatSVGIcon("./icon/export_excel.svg"));

        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTop = new javax.swing.JPanel();
        btnThemPX = new javax.swing.JButton();
        btnChiTietPX = new javax.swing.JButton();
        btnHuyPX = new javax.swing.JButton();
        btnXuatExcelPX = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnTimKiem = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPhieuXuat = new javax.swing.JTable();
        pnlLoc = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        pnlTop.setBackground(new java.awt.Color(255, 255, 255));
        pnlTop.setPreferredSize(new java.awt.Dimension(1200, 70));

        btnThemPX.setText("Thêm");
        pnlTop.add(btnThemPX);

        btnChiTietPX.setText("Chi tiết");
        btnChiTietPX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChiTietPXActionPerformed(evt);
            }
        });
        pnlTop.add(btnChiTietPX);

        btnHuyPX.setText("Hủy phiếu");
        btnHuyPX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyPXActionPerformed(evt);
            }
        });
        pnlTop.add(btnHuyPX);

        btnXuatExcelPX.setText("Xuất excel");
        btnXuatExcelPX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatExcelPXActionPerformed(evt);
            }
        });
        pnlTop.add(btnXuatExcelPX);

        jLabel1.setText("Tìm kiếm :");
        pnlTop.add(jLabel1);

        btnTimKiem.setPreferredSize(new java.awt.Dimension(200, 30));
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });
        pnlTop.add(btnTimKiem);

        add(pnlTop, java.awt.BorderLayout.NORTH);

        tblPhieuXuat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã phiếu xuất", "Khách hàng", "Nhân viên nhập", "Thời gian", "Tổng tiền"
            }
        ));
        jScrollPane1.setViewportView(tblPhieuXuat);

        pnlLoc.setBackground(new java.awt.Color(0, 102, 102));
        pnlLoc.setPreferredSize(new java.awt.Dimension(270, 700));

        jLabel2.setText("Lọc ở đây");

        javax.swing.GroupLayout pnlLocLayout = new javax.swing.GroupLayout(pnlLoc);
        pnlLoc.setLayout(pnlLocLayout);
        pnlLocLayout.setHorizontalGroup(
            pnlLocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLocLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );
        pnlLocLayout.setVerticalGroup(
            pnlLocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLocLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(523, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 925, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(pnlLoc, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE))
                .addContainerGap())
        );

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnChiTietPXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChiTietPXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChiTietPXActionPerformed

    private void btnHuyPXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyPXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHuyPXActionPerformed

    private void btnXuatExcelPXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatExcelPXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXuatExcelPXActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTimKiemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChiTietPX;
    private javax.swing.JButton btnHuyPX;
    private javax.swing.JButton btnThemPX;
    private javax.swing.JTextField btnTimKiem;
    private javax.swing.JButton btnXuatExcelPX;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlLoc;
    private javax.swing.JPanel pnlTop;
    private javax.swing.JTable tblPhieuXuat;
    // End of variables declaration//GEN-END:variables
}
