package GUI;

import BUS.SanPhamBus;
import DAO.KhuVucKhoDAO;
import DAO.LoaiDAO;
import DAO.ThuongHieuDAO;
import DAO.XuatXuDAO;
import DTO.SanPhamDTO;
import GUI.SPham.ThemSanPham;
import GUI.SanPham;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import static java.awt.AWTEventMulticaster.add;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author ADMIN
 */
public class SanPham extends javax.swing.JPanel implements ActionListener{

    /**
     * Creates new form SanPham
     */
    DefaultTableModel tblModel;

    public SanPham() throws IOException {
        initComponents();
        addIcon();
        tblSanPham.setFocusable(false);
        tblSanPham.setDefaultEditor(Object.class, null); // set ko cho sửa dữ liệu trên table
        tblSanPham.getColumnModel().getColumn(1).setPreferredWidth(180);
        tblSanPham.setFocusable(false);
        tblSanPham.setAutoCreateRowSorter(true);
//        tblModel = new DefaultTableModel();
//        String[] header = new String[]{"Mã SP", "Tên sản phẩm", "Số lượng tồn","Thương hiệu", "Hệ điều hành", "Kích thước màn","Chip xử lý","Dung lượng pin","Xuất xứ", "Khu vực kho"};
//        tblModel.setColumnIdentifiers(header);
//        tblSanPham.setModel(tblModel);
//        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
//        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
//        TableColumnModel columnModel = tblSanPham.getColumnModel();

//        for (int i = 0; i < 10; i++) {
//            if (i != 1) {
//                columnModel.getColumn(i).setCellRenderer(centerRenderer);
//            }
//        }
//        int a = 1;
//        tblSanPham.getModel().setValueAt(a, 1, 1);

        btnThemSP.addActionListener(this);
        btnSuaSP.addActionListener(this);
        
        setLayout(new BorderLayout());
        setPreferredSize(new Dimension(1200,800));
        this.add(pnlTop,BorderLayout.NORTH);
        this.add(pnlCenter,BorderLayout.CENTER);
        
        
        hienThiListSanPham();
    }
    
    SanPhamBus sanPhamBus ;
    ThuongHieuDAO thuongHieuDAO;
    LoaiDAO loaiDAO;
    XuatXuDAO xuatXuDAO;
    KhuVucKhoDAO khuVucKhoDAO;
    
   private void hienThiListSanPham() {
    sanPhamBus = new SanPhamBus();
    thuongHieuDAO = new ThuongHieuDAO();
    loaiDAO = new LoaiDAO();
    xuatXuDAO = new XuatXuDAO();
    khuVucKhoDAO = new KhuVucKhoDAO();
    ArrayList<SanPhamDTO> listSanPham = sanPhamBus.getAllSanPham();
    DefaultTableModel model = (DefaultTableModel) tblSanPham.getModel();
    model.setRowCount(0);
    for (SanPhamDTO sanPham : listSanPham) {
        Object[] row = {
            sanPham.getMasp(), 
            sanPham.getTensp(), 
            sanPham.getSoluongton(), 
            sanPham.getSize(), 
            loaiDAO.selectById(sanPham.getLoai()).getTenloai(),
            thuongHieuDAO.selectById(sanPham.getThuonghieu()).getTenthuonghieu(),
            xuatXuDAO.selectById(sanPham.getXuatxu()).getTenxuatxu(), // Giá trị ở giữa thứ 7
            khuVucKhoDAO.selectById(sanPham.getKhuvuckho()).getTenkhuvuc(),
        };
        model.addRow(row);
    }

    // Tạo renderer để hiển thị nội dung ở giữa ô
    DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
    centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);

    // Áp dụng renderer cho từng cột trong bảng
    for (int i = 0; i < tblSanPham.getColumnCount(); i++) {
        tblSanPham.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
    }
}
    
    
    private void addIcon() {
        btnThemSP.setIcon(new FlatSVGIcon("./icon/add.svg"));
        btnSuaSP.setIcon(new FlatSVGIcon("./icon/edit.svg"));
        btnXoaSP.setIcon(new FlatSVGIcon("./icon/delete.svg"));
        btnXuatExcelSP.setIcon(new FlatSVGIcon("./icon/export_excel.svg"));
        btnChiTietSP.setIcon(new FlatSVGIcon("./icon/detail.svg"));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTop = new javax.swing.JPanel();
        btnThemSP = new javax.swing.JButton();
        btnSuaSP = new javax.swing.JButton();
        btnXoaSP = new javax.swing.JButton();
        btnChiTietSP = new javax.swing.JButton();
        btnXuatExcelSP = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnTimKiem = new javax.swing.JTextField();
        pnlCenter = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSanPham = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1200, 800));
        setLayout(new java.awt.BorderLayout());

        pnlTop.setBackground(new java.awt.Color(255, 255, 255));
        pnlTop.setPreferredSize(new java.awt.Dimension(1200, 70));

        btnThemSP.setText("Thêm");
        btnThemSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemSPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnThemSPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnThemSPMouseExited(evt);
            }
        });
        btnThemSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemSPActionPerformed(evt);
            }
        });
        pnlTop.add(btnThemSP);

        btnSuaSP.setText("Sửa");
        btnSuaSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaSPActionPerformed(evt);
            }
        });
        pnlTop.add(btnSuaSP);

        btnXoaSP.setText("Xóa");
        btnXoaSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaSPActionPerformed(evt);
            }
        });
        pnlTop.add(btnXoaSP);

        btnChiTietSP.setText("Chi tiết");
        btnChiTietSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChiTietSPActionPerformed(evt);
            }
        });
        pnlTop.add(btnChiTietSP);

        btnXuatExcelSP.setText("Xuất excel");
        btnXuatExcelSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatExcelSPActionPerformed(evt);
            }
        });
        pnlTop.add(btnXuatExcelSP);

        jLabel1.setLabelFor(btnTimKiem);
        jLabel1.setText("Tìm kiếm :");
        pnlTop.add(jLabel1);

        btnTimKiem.setPreferredSize(new java.awt.Dimension(200, 30));
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });
        pnlTop.add(btnTimKiem);

        add(pnlTop, java.awt.BorderLayout.NORTH);

        pnlCenter.setPreferredSize(new java.awt.Dimension(1200, 700));

        tblSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Số lượng tồn", "Size", "Loại", "Thương hiệu", "Xuất xứ", "Khu vực kho"
            }
        ));
        jScrollPane2.setViewportView(tblSanPham);

        javax.swing.GroupLayout pnlCenterLayout = new javax.swing.GroupLayout(pnlCenter);
        pnlCenter.setLayout(pnlCenterLayout);
        pnlCenterLayout.setHorizontalGroup(
            pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
        );
        pnlCenterLayout.setVerticalGroup(
            pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
        );

        add(pnlCenter, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSuaSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSuaSPActionPerformed

    private void btnXoaSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaSPActionPerformed

    private void btnXuatExcelSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatExcelSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXuatExcelSPActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnChiTietSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChiTietSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChiTietSPActionPerformed

    private void btnThemSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemSPActionPerformed

    private void btnThemSPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemSPMouseEntered
        // TODO add your handling code here:
        btnThemSP.setBackground(Color.red);
    }//GEN-LAST:event_btnThemSPMouseEntered

    private void btnThemSPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemSPMouseExited
        // TODO add your handling code here:
        btnThemSP.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnThemSPMouseExited

    private void btnThemSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemSPMouseClicked
        // TODO add your handling code here:
        if ( !btnThemSP.isSelected()){
         btnThemSP.setBackground(Color.WHITE);
        } else {
            btnThemSP.setBackground(Color.BLUE);
        }
    }//GEN-LAST:event_btnThemSPMouseClicked
    ThemSanPham themSanPham;

    @Override
    public void actionPerformed(ActionEvent e){
        if ( e.getSource() == btnThemSP){
            themSanPham = new ThemSanPham();
            themSanPham.setLocationRelativeTo(null);
            themSanPham.setVisible(true);
        } 
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChiTietSP;
    private javax.swing.JButton btnSuaSP;
    private javax.swing.JButton btnThemSP;
    private javax.swing.JTextField btnTimKiem;
    private javax.swing.JButton btnXoaSP;
    private javax.swing.JButton btnXuatExcelSP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnlCenter;
    private javax.swing.JPanel pnlTop;
    private javax.swing.JTable tblSanPham;
    // End of variables declaration//GEN-END:variables
}
