package GUI;

import GUI.ThuocTinhSP.Loai;
import GUI.ThuocTinhSP.ThuongHieu;
import GUI.ThuocTinhSP.XuatXu;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Container;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author ADMIN
 */
public class ThuocTinh extends javax.swing.JPanel {

    /**
     * Creates new form ThuocTinh
     */
    ThuongHieu thuongHieu;
    Loai loai;
    XuatXu xuatXu;

    public ThuocTinh() {
        initComponents();
        contentCenter.setLayout(new BorderLayout()); // Thiết lập layout cho contentCenter
        btnThuongHieuActionPerformed(null);
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnThuongHieu = new javax.swing.JButton();
        btnLoai = new javax.swing.JButton();
        btnXuatXu = new javax.swing.JButton();
        contentCenter = new javax.swing.JPanel();

        btnThuongHieu.setText("Thương Hiệu");
        btnThuongHieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThuongHieuActionPerformed(evt);
            }
        });

        btnLoai.setText("Loại");
        btnLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoaiActionPerformed(evt);
            }
        });

        btnXuatXu.setText("Xuất xứ");
        btnXuatXu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatXuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contentCenterLayout = new javax.swing.GroupLayout(contentCenter);
        contentCenter.setLayout(contentCenterLayout);
        contentCenterLayout.setHorizontalGroup(
            contentCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 754, Short.MAX_VALUE)
        );
        contentCenterLayout.setVerticalGroup(
            contentCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnThuongHieu, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(btnLoai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXuatXu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addComponent(contentCenter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThuongHieu, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(btnLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnXuatXu, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(260, Short.MAX_VALUE))
            .addComponent(contentCenter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThuongHieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThuongHieuActionPerformed
        System.out.println("Called btnThuongHieuActionPerformed");
        thuongHieu = new ThuongHieu();
        addPanel(contentCenter, thuongHieu);
    }//GEN-LAST:event_btnThuongHieuActionPerformed

    private void btnXuatXuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatXuActionPerformed
        // TODO add your handling code here:
        xuatXu = new XuatXu();
        addPanel(contentCenter, xuatXu);
    }//GEN-LAST:event_btnXuatXuActionPerformed

    private void btnLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoaiActionPerformed
        // TODO add your handling code here:
        loai = new Loai();
        addPanel(contentCenter, loai);
    }//GEN-LAST:event_btnLoaiActionPerformed
    public void addPanel(Container contentCenter, JPanel panel) {
        panel.setSize(contentCenter.getSize());
        contentCenter.removeAll();
        contentCenter.add(panel).setVisible(true);
        contentCenter.revalidate();
        contentCenter.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoai;
    private javax.swing.JButton btnThuongHieu;
    private javax.swing.JButton btnXuatXu;
    private javax.swing.JPanel contentCenter;
    // End of variables declaration//GEN-END:variables
}
